theme = "onedark-custom"

[editor]
rulers = [80, 100]

[editor.lsp]
display-inlay-hints = true

[editor.file-picker]
hidden = false
max-depth = 5

[keys.normal]
C-s = ":w"
C-g = ":open ~/git/"
C-d = ":open ~/git/github.com/nicholastmosher/dotfiles/"
C-p = ":open ~/git/github.com/nicholastmosher/dotfiles/home/.config/helix/config.toml"
C-r = [":reload", ":config-reload ~/git/github.com/nicholastmosher/dotfiles/home/.config/helix/config.toml"]
C-e = "file_picker_in_current_directory"
G = "goto_last_line"

[keys.normal.g]
k = "goto_file_start"
j = "goto_last_line"

[keys.normal.b]
b = "buffer_picker"
n = "goto_next_buffer"
p = "goto_previous_buffer"
h = "jump_view_left"
j = "jump_view_down"
k = "jump_view_up"
l = "jump_view_right"

# Use ]] and [[ to cycle through diagnostics
[keys.normal."]"]
"]" = "goto_next_diag"
[keys.normal."["]
"[" = "goto_prev_diag"

[keys.insert]
j = { j = "normal_mode" }

