[[language]]
name = "nix"
scope = "source.nix"
file-types = ["nix"]
comment-token = "#"
indent = { tab-width = 2, unit = "  " }
language-server = { command = "rnix-lsp" }
auto-format = true

[[language]]
name = "rust"
scope = "source.rust"
file-types = ["rs"]
language-server = { command = "rustup", args = ["run", "stable", "rust-analyzer"] }
